import type { Product } from "@/types/product";

export const openSourceProjects: Product[] = [
  {
    id: "the-home-versus",
    name: {
      en: "The Home Versus",
      vi: "The Home Versus",
      hi: "The Home Versus",
      km: "The Home Versus",
      th: "The Home Versus",
      id: "The Home Versus",
      fil: "The Home Versus",
      de: "The Home Versus",
      fr: "The Home Versus",
    },
    description: {
      en: "Editorial product comparisons and practical recommendations for real households.",
      vi: "So sánh sản phẩm theo phong cách biên tập cùng các gợi ý thực tế cho gia đình hiện đại.",
      hi: "वास्तविक घरों के लिए संपादकीय शैली की उत्पाद तुलनाएं और व्यावहारिक सिफारिशें।",
      km: "ការប្រៀបធៀបផលិតផលបែបវិចារណកថា និងអនុសាសន៍ជាក់ស្តែងសម្រាប់គ្រួសារពិតប្រាកដ។",
      th: "การเปรียบเทียบสินค้าเชิงบรรณาธิการและคำแนะนำที่ใช้งานได้จริงสำหรับครัวเรือนจริง",
      id: "Perbandingan produk bergaya editorial dan rekomendasi praktis untuk rumah tangga nyata.",
      fil: "Mga editorial na paghahambing ng produkto at praktikal na rekomendasyon para sa tunay na mga sambahayan.",
      de: "Redaktionelle Produktvergleiche und praktische Empfehlungen fuer echte Haushalte.",
      fr: "Des comparaisons de produits de style editorial et des recommandations pratiques pour de vrais foyers.",
    },
    category: {
      en: "Open Source",
      vi: "Mã nguồn mở",
      hi: "ओपन सोर्स",
      km: "Open Source",
      th: "โอเพนซอร์ส",
      id: "Open Source",
      fil: "Open Source",
      de: "Open Source",
      fr: "Open Source",
    },
    stack: ["TypeScript", "Next.js"],
    image: "/graphic/the-home-versus.png",
    githubLink: "https://github.com/nexa-tech-solution/the-home-versus",
  },
  {
    id: "react-native-simple-fs",
    name: {
      en: "React Native Simple FS",
      vi: "React Native Simple FS",
      hi: "React Native Simple FS",
      km: "React Native Simple FS",
      th: "React Native Simple FS",
      id: "React Native Simple FS",
      fil: "React Native Simple FS",
      de: "React Native Simple FS",
      fr: "React Native Simple FS",
    },
    description: {
      en: "A lightweight React Native file-system library built as a showcase utility for storage, file access, and export flows.",
      vi: "Một thư viện hệ thống tệp React Native nhẹ được xây dựng như một tiện ích trình diễn cho lưu trữ, truy cập tệp và luồng xuất.",
      hi: "स्टोरेज, फ़ाइल एक्सेस और निर्यात प्रवाह के लिए एक शोकेस उपयोगिता के रूप में निर्मित एक हल्का रिएक्ट नेटिव फ़ाइल-सिस्टम लाइब्रेरी।",
      km: "បណ្ណាល័យប្រព័ន្ធឯកសារ React Native ទំងន់ស្រាលដែលបានបង្កើតឡើងជាឧបករណ៍បង្ហាញសម្រាប់ការផ្ទុក, ការចូលប្រើឯកសារ និងចរន្តនាំចេញ។",
      th: "ไลบรารีระบบไฟล์ React Native น้ำหนักเบาที่สร้างขึ้นเป็นยูทิลิตี้แสดงสำหรับการจัดเก็บ การเข้าถึงไฟล์ และการส่งออก",
      id: "Perpustakaan sistem file React Native ringan yang dibangun sebagai utilitas showcase untuk penyimpanan, akses file, dan alur ekspor.",
      fil: "Isang magaan na React Native file-system library na itinayo bilang isang showcase utility para sa storage, file access, at export flows.",
      de: "Eine leichte React Native-Dateisystembibliothek, die als Showcase-Dienstprogramm für Speicher, Dateizugriff und Exportabläufe entwickelt wurde.",
      fr: "Une bibliothèque de système de fichiers React Native légère construite comme un utilitaire de vitrine pour le stockage, l'accès aux fichiers et les flux d'exportation.",
    },
    category: {
      en: "Open Source",
      vi: "Mã nguồn mở",
      hi: "ओपन सोर्स",
      km: "Open Source",
      th: "โอเพนซอร์ส",
      id: "Open Source",
      fil: "Open Source",
      de: "Open Source",
      fr: "Open Source",
    },
    stack: ["React Navtive", "TypeScript", "Hooks"],
    githubLink: "https://www.npmjs.com/package/react-native-simple-fs",
    image: "/graphic/react-native-simple-fs.png",
  },
  {
    id: "time-converter-world-clock",
    name: {
      en: "Time Converter - World Clock",
      vi: "Time Converter - World Clock",
      hi: "Time Converter - World Clock",
      km: "Time Converter - World Clock",
      th: "Time Converter - World Clock",
      id: "Time Converter - World Clock",
      fil: "Time Converter - World Clock",
      de: "Time Converter - World Clock",
      fr: "Time Converter - World Clock",
    },
    description: {
      en: "Plan meetings and travel across global time zones from your phone.",
      vi: "Lên kế hoạch họp và di chuyển qua các múi giờ toàn cầu ngay trên điện thoại.",
      hi: "अपने फोन से वैश्विक समय क्षेत्रों के अनुसार मीटिंग और यात्रा की योजना बनाएं।",
      km: "រៀបចំផែនការប្រជុំ និងការធ្វើដំណើរឆ្លងកាត់តំបន់ពេលវេលាពិភពលោកពីទូរស័ព្ទរបស់អ្នក។",
      th: "วางแผนการประชุมและการเดินทางข้ามเขตเวลาทั่วโลกจากโทรศัพท์ของคุณ",
      id: "Rencanakan rapat dan perjalanan lintas zona waktu global dari ponsel Anda.",
      fil: "Planuhin ang mga meeting at biyahe sa iba’t ibang global time zone mula sa iyong phone.",
      de: "Plane Meetings und Reisen ueber globale Zeitzonen hinweg direkt von deinem Smartphone.",
      fr: "Planifiez reunions et voyages a travers les fuseaux horaires mondiaux depuis votre telephone.",
    },
    category: {
      en: "Mobile",
      vi: "Di động",
      hi: "मोबाइल",
      km: "ទូរស័ព្ទ",
      th: "มือถือ",
      id: "Seluler",
      fil: "Mobile",
      de: "Mobil",
      fr: "Mobile",
    },
    stack: ["Next.js", "TypeScript"],
    image: "/graphic/time-converter.png",
    githubLink: "https://github.com/nexa-tech-solution/time-converter",
  },
];
