import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "the-home-versus",
    name: {
      en: "The Home Versus",
      vi: "The Home Versus",
      hi: "The Home Versus",
      km: "The Home Versus",
      th: "The Home Versus",
      id: "The Home Versus",
      fil: "The Home Versus",
      de: "The Home Versus",
      fr: "The Home Versus",
    },
    description: {
      en: "Editorial product comparisons and practical recommendations for real households.",
      vi: "So sánh sản phẩm theo phong cách biên tập cùng các gợi ý thực tế cho gia đình hiện đại.",
      hi: "वास्तविक घरों के लिए संपादकीय शैली की उत्पाद तुलनाएं और व्यावहारिक सिफारिशें।",
      km: "ការប្រៀបធៀបផលិតផលបែបវិចារណកថា និងអនុសាសន៍ជាក់ស្តែងសម្រាប់គ្រួសារពិតប្រាកដ។",
      th: "การเปรียบเทียบสินค้าเชิงบรรณาธิการและคำแนะนำที่ใช้งานได้จริงสำหรับครัวเรือนจริง",
      id: "Perbandingan produk bergaya editorial dan rekomendasi praktis untuk rumah tangga nyata.",
      fil: "Mga editorial na paghahambing ng produkto at praktikal na rekomendasyon para sa tunay na mga sambahayan.",
      de: "Redaktionelle Produktvergleiche und praktische Empfehlungen fuer echte Haushalte.",
      fr: "Des comparaisons de produits de style editorial et des recommandations pratiques pour de vrais foyers.",
    },
    category: {
      en: "Web",
      vi: "Web",
      hi: "Web",
      km: "Web",
      th: "Web",
      id: "Web",
      fil: "Web",
      de: "Web",
      fr: "Web",
    },
    stack: ["Next.js"],
    image: "/graphic/the-home-versus.png",
    wide: true,
    tall: true,
    link: "https://thehomeversus.com/",
  },
  {
    id: "mystic-tarot",
    name: {
      en: "Mystic Tarot",
      vi: "Mystic Tarot",
      hi: "Mystic Tarot",
      km: "Mystic Tarot",
      th: "Mystic Tarot",
      id: "Mystic Tarot",
      fil: "Mystic Tarot",
      de: "Mystic Tarot",
      fr: "Mystic Tarot",
    },
    description: {
      en: "A reflective tarot experience for self-discovery and daily guidance.",
      vi: "Trải nghiệm tarot suy ngẫm cho việc tự khám phá và hướng dẫn hàng ngày.",
      hi: "आत्म-खोज और दैनिक मार्गदर्शन के लिए एक चिंतनशील टैरो अनुभव।",
      km: "បទពិសោធន៍ tarot សម្រាប់ការស្វែងរកខ្លួនឯង និងការណែនាំប្រចាំថ្ងៃ។",
      th: "ประสบการณ์ไพ่ทาโรต์เพื่อการค้นพบตัวเองและคำแนะนำประจำวัน",
      id: "Pengalaman tarot reflektif untuk penemuan diri dan panduan harian.",
      fil: "Isang reflective na karanasan ng tarot para sa self-discovery at pang-araw-araw na gabay.",
      de: "Ein reflektierendes Tarot-Erlebnis zur Selbstfindung und täglichen Orientierung.",
      fr: "Une expérience de tarot réflective pour la découverte de soi et les conseils quotidiens.",
    },
    category: {
      en: "Web",
      vi: "Web",
      hi: "Web",
      km: "Web",
      th: "Web",
      id: "Web",
      fil: "Web",
      de: "Web",
      fr: "Web",
    },
    stack: ["React", "Tailwind", "Node.js"],
    image: "/graphic/tarot-destiny.webp",
    wide: true,
    link: "https://tarrot-web-app.vercel.app/",
    playStoreLink:
      "https://play.google.com/store/apps/details?id=com.nexa_tarrot_app",
  },
  {
    id: "petpal",
    name: {
      en: "PetPal",
      vi: "PetPal",
      hi: "PetPal",
      km: "PetPal",
      th: "PetPal",
      id: "PetPal",
      fil: "PetPal",
      de: "PetPal",
      fr: "PetPal",
    },
    description: {
      en: "An expressive virtual pet companion powered by conversational AI.",
      vi: "Thú cưng ảo biểu cảm được hỗ trợ bởi AI hội thoại.",
      hi: "संवादात्मक AI द्वारा संचालित एक अभिव्यंजक वर्चुअल पेट साथी।",
      km: "សត្វចិញ្ចឹមនិម្មិតដែលដំណើរការដោយ AI សន្ទនា។",
      th: "สัตว์เลี้ยงเสมือนจริงที่ขับเคลื่อนด้วย AI สนทนา",
      id: "Hewan peliharaan virtual ekspresif yang didukung AI percakapan.",
      fil: "Isang expressive na virtual pet companion na pinapagana ng conversational AI.",
      de: "Ein ausdrucksstarker virtueller Haustierbegleiter mit konversationeller KI.",
      fr: "Un compagnon animal virtuel expressif propulsé par l'IA conversationnelle.",
    },
    category: {
      en: "Web",
      vi: "Web",
      hi: "Web",
      km: "Web",
      th: "Web",
      id: "Web",
      fil: "Web",
      de: "Web",
      fr: "Web",
    },
    stack: ["Next.js", "Gemini", "Rive"],
    image: "/graphic/petpal.png",
    tall: true,
    link: "https://pet-simulator-sigma.vercel.app/",
    playStoreLink:
      "https://play.google.com/store/apps/details?id=com.pet_simulator",
  },
  {
    id: "resize-image",
    name: {
      en: "Resize Image",
      vi: "Resize Image",
      hi: "Resize Image",
      km: "Resize Image",
      th: "Resize Image",
      id: "Resize Image",
      fil: "Resize Image",
      de: "Resize Image",
      fr: "Resize Image",
    },
    description: {
      en: "A private browser tool for fast image resizing, compression, and conversion.",
      vi: "Công cụ trình duyệt riêng tư để thay đổi kích thước, nén và chuyển đổi ảnh nhanh.",
      hi: "तेज़ इमेज रिसाइज़िंग, कम्प्रेशन और कन्वर्शन के लिए एक निजी ब्राउज़र टूल।",
      km: "ឧបករណ៍កម្មវិធីរុករកឯកជនសម្រាប់ការផ្លាស់ប្តូរទំហំ ការបង្ហាប់ និងការបម្លែងរូបភាព។",
      th: "เครื่องมือเบราว์เซอร์ส่วนตัวสำหรับปรับขนาด บีบอัด และแปลงไฟล์ภาพ",
      id: "Alat browser pribadi untuk mengubah ukuran, kompresi, dan konversi gambar dengan cepat.",
      fil: "Isang private browser tool para sa mabilis na image resizing, compression, at conversion.",
      de: "Ein privates Browser-Tool für schnelle Bildgrößenanpassung, Komprimierung und Konvertierung.",
      fr: "Un outil de navigateur privé pour le redimensionnement, la compression et la conversion rapides d'images.",
    },
    category: {
      en: "Tool",
      vi: "Công cụ",
      hi: "टूल",
      km: "ឧបករណ៍",
      th: "เครื่องมือ",
      id: "Alat",
      fil: "Tool",
      de: "Werkzeug",
      fr: "Outil",
    },
    stack: ["Web Tool", "Image Processing"],
    image: "/graphic/resize-image.png",
    wide: false,
    link: "https://resizeimage.tech/",
  },
  {
    id: "time-converter",
    name: {
      en: "Time Converter",
      vi: "Time Converter",
      hi: "Time Converter",
      km: "Time Converter",
      th: "Time Converter",
      id: "Time Converter",
      fil: "Time Converter",
      de: "Time Converter",
      fr: "Time Converter",
    },
    description: {
      en: "Compare cities and time zones without the friction of manual calculations.",
      vi: "So sánh các thành phố và múi giờ mà không cần phải tính toán thủ công rườm rà.",
      hi: "मैन्युअल गणनाओं की झंझट के बिना शहरों और समय क्षेत्रों की तुलना करें।",
      km: "ប្រៀបធៀបទីក្រុង និងតំបន់ពេលវេលា ដោយមិនចាំបាច់គណនាដោយដៃឱ្យស្មុគស្មាញ។",
      th: "เปรียบเทียบเมืองและเขตเวลาได้โดยไม่ต้องวุ่นวายกับการคำนวณด้วยตนเอง",
      id: "Bandingkan kota dan zona waktu tanpa repot melakukan perhitungan manual.",
      fil: "Ihambing ang mga lungsod at time zone nang hindi na dumaraan sa abalang manual na pagkalkula.",
      de: "Vergleiche Staedte und Zeitzonen ohne den Aufwand manueller Berechnungen.",
      fr: "Comparez les villes et les fuseaux horaires sans les frictions des calculs manuels.",
    },
    category: {
      en: "Tool",
      vi: "Công cụ",
      hi: "टूल",
      km: "ឧបករណ៍",
      th: "เครื่องมือ",
      id: "Alat",
      fil: "Tool",
      de: "Werkzeug",
      fr: "Outil",
    },
    stack: ["React", "Productivity", "React Native"],
    image: "/graphic/time-converter.png",
    tall: true,
    //link: "https://time-converter-woad-iota.vercel.app/",
    appStoreLink:
      "https://apps.apple.com/us/app/time-converter-world-clock/id6780116305",
    playStoreLink:
      "https://play.google.com/store/apps/details?id=nexa.timeconverter.com",
  },
  {
    id: "scane-qr",
    name: {
      en: "Scan QR",
      vi: "Scan QR",
      hi: "Scan QR",
      km: "Scan QR",
      th: "Scan QR",
      id: "Scan QR",
      fil: "Scan QR",
      de: "Scan QR",
      fr: "Scan QR",
    },
    description: {
      en: "A focused QR code and barcode scanner for Android and iOS.",
      vi: "Trình quét mã QR và mã vạch gọn gàng dành cho Android và iOS.",
      hi: "Android और iOS के लिए एक केंद्रित QR कोड और बारकोड स्कैनर।",
      km: "កម្មវិធីស្កេនកូដ QR និងបាកូដដែលផ្តោតសម្រាប់ Android និង iOS។",
      th: "เครื่องสแกนคิวอาร์โค้ดและบาร์โค้ดแบบเน้นการใช้งานสำหรับ Android และ iOS",
      id: "Pemindai kode QR dan barcode yang fokus untuk Android dan iOS.",
      fil: "Isang nakatuong QR code at barcode scanner para sa Android at iOS.",
      de: "Ein fokussierter QR-Code- und Barcode-Scanner fuer Android und iOS.",
      fr: "Un scanner de QR codes et de codes-barres concis pour Android et iOS.",
    },
    category: {
      en: "Tool",
      vi: "Công cụ",
      hi: "टूल",
      km: "ឧបករណ៍",
      th: "เครื่องมือ",
      id: "Alat",
      fil: "Tool",
      de: "Werkzeug",
      fr: "Outil",
    },
    stack: ["React", "Productivity", "React Native"],
    image: "/graphic/scanqr.png",
    wide: false,
    //link: "https://time-converter-woad-iota.vercel.app/",
    appStoreLink:
      "https://apps.apple.com/us/app/time-converter-world-clock/id6780116305",
    playStoreLink:
      "https://play.google.com/store/apps/details?id=nexa.timeconverter.com",
  },
  {
    id: "fieldstamp-gps-camera",
    name: {
      en: "FieldStamp GPS Camera",
      vi: "FieldStamp GPS Camera",
      hi: "FieldStamp GPS Camera",
      km: "FieldStamp GPS Camera",
      th: "FieldStamp GPS Camera",
      id: "FieldStamp GPS Camera",
      fil: "FieldStamp GPS Camera",
      de: "FieldStamp GPS Camera",
      fr: "FieldStamp GPS Camera",
    },
    description: {
      en: "Capture photos with GPS stamps, project notes, and exportable location details.",
      vi: "Chụp ảnh kèm dấu GPS, ghi chú dự án và thông tin vị trí có thể xuất ra.",
      hi: "GPS स्टैम्प, प्रोजेक्ट नोट्स और एक्सपोर्ट की जा सकने वाली लोकेशन डिटेल्स के साथ फोटो कैप्चर करें।",
      km: "ថតរូបជាមួយស្លាក GPS កំណត់ចំណាំគម្រោង និងព័ត៌មានទីតាំងដែលអាចនាំចេញបាន។",
      th: "ถ่ายภาพพร้อมตราประทับ GPS บันทึกโครงการ และรายละเอียดตำแหน่งที่ส่งออกได้",
      id: "Ambil foto dengan stempel GPS, catatan proyek, dan detail lokasi yang dapat diekspor.",
      fil: "Kumuha ng mga larawan na may GPS stamps, project notes, at nae-export na detalye ng lokasyon.",
      de: "Erfasse Fotos mit GPS-Stempeln, Projektnotizen und exportierbaren Standortdetails.",
      fr: "Capturez des photos avec des marqueurs GPS, des notes de projet et des details de localisation exportables.",
    },
    category: {
      en: "Mobile",
      vi: "Di động",
      hi: "मोबाइल",
      km: "ទូរស័ព្ទ",
      th: "มือถือ",
      id: "Seluler",
      fil: "Mobile",
      de: "Mobil",
      fr: "Mobile",
    },
    stack: ["React Native", "GPS", "Camera", "PDF"],
    image: "/graphic/fieldstamp-camera.png",
    wide: true,
    appStoreLink:
      "https://apps.apple.com/us/app/fieldstamp-gps-camera/id6786527961",
    playStoreLink:
      "https://play.google.com/store/apps/details?id=com.fieldstamp.free",
  },
  {
    id: "smart-currency-converter",
    name: {
      en: "Smart Currency Converter",
      vi: "Smart Currency Converter",
      hi: "Smart Currency Converter",
      km: "Smart Currency Converter",
      th: "Smart Currency Converter",
      id: "Smart Currency Converter",
      fil: "Smart Currency Converter",
      de: "Smart Currency Converter",
      fr: "Smart Currency Converter",
    },
    description: {
      en: "Fast exchange-rate conversion with useful offline calculations.",
      vi: "Chuyển đổi tỷ giá nhanh cùng các phép tính ngoại tuyến hữu ích.",
      hi: "उपयोगी ऑफलाइन गणनाओं के साथ तेज़ विनिमय-दर रूपांतरण।",
      km: "បម្លែងអត្រាប្តូរប្រាក់បានលឿន ជាមួយការគណនាក្រៅបណ្ដាញដែលមានប្រយោជន៍។",
      th: "แปลงอัตราแลกเปลี่ยนได้รวดเร็วพร้อมการคำนวณออฟไลน์ที่มีประโยชน์",
      id: "Konversi nilai tukar cepat dengan perhitungan offline yang berguna.",
      fil: "Mabilis na currency conversion na may kapaki-pakinabang na offline calculations.",
      de: "Schnelle Wechselkursumrechnung mit nützlichen Offline-Berechnungen.",
      fr: "Conversion rapide des taux de change avec des calculs hors ligne utiles.",
    },
    category: {
      en: "Mobile",
      vi: "Di động",
      hi: "मोबाइल",
      km: "ទូរស័ព្ទ",
      th: "มือถือ",
      id: "Seluler",
      fil: "Mobile",
      de: "Mobil",
      fr: "Mobile",
    },
    stack: ["React Native", "Currency", "Offline"],
    image: "/graphic/currency-converter.png",
    wide: false,
    appStoreLink:
      "https://apps.apple.com/us/app/currency-unit-converter/id6780219094",
    playStoreLink:
      "https://play.google.com/store/apps/details?id=com.currencyunitconverter",
  },
  {
    id: "loan-estimator",
    name: {
      en: "Loan Estimator",
      vi: "Loan Estimator",
      hi: "Loan Estimator",
      km: "Loan Estimator",
      th: "Loan Estimator",
      id: "Loan Estimator",
      fil: "Loan Estimator",
      de: "Loan Estimator",
      fr: "Loan Estimator",
    },
    description: {
      en: "Estimate repayments and export clear loan calculation reports.",
      vi: "Ước tính khoản trả góp và xuất báo cáo tính toán khoản vay rõ ràng.",
      hi: "भुगतान का अनुमान लगाएं और स्पष्ट लोन कैलकुलेशन रिपोर्ट एक्सपोर्ट करें।",
      km: "ប៉ាន់ស្មានការសងត្រឡប់ និងនាំចេញរបាយការណ៍គណនាប្រាក់កម្ចីដែលច្បាស់លាស់។",
      th: "ประเมินการผ่อนชำระและส่งออกรายงานการคำนวณเงินกู้ที่ชัดเจน",
      id: "Perkirakan cicilan dan ekspor laporan perhitungan pinjaman yang jelas.",
      fil: "Tantiyahin ang mga bayarin at mag-export ng malinaw na loan calculation reports.",
      de: "Schaetze Rueckzahlungen und exportiere klare Darlehensberechnungsberichte.",
      fr: "Estimez les remboursements et exportez des rapports clairs de calcul de pret.",
    },
    category: {
      en: "Mobile",
      vi: "Di động",
      hi: "मोबाइल",
      km: "ទូរស័ព្ទ",
      th: "มือถือ",
      id: "Seluler",
      fil: "Mobile",
      de: "Mobil",
      fr: "Mobile",
    },
    stack: ["React Native", "Finance", "PDF"],
    image: "/graphic/easy-loan-calculator.webp",
    wide: false,
    appStoreLink:
      "https://apps.apple.com/us/app/easy-loan-estimator/id6779272088",
    playStoreLink:
      "https://play.google.com/store/apps/details?id=com.nexa.loan.estimator",
  },
  {
    id: "time-converter-world-clock",
    name: {
      en: "Time Converter - World Clock",
      vi: "Time Converter - World Clock",
      hi: "Time Converter - World Clock",
      km: "Time Converter - World Clock",
      th: "Time Converter - World Clock",
      id: "Time Converter - World Clock",
      fil: "Time Converter - World Clock",
      de: "Time Converter - World Clock",
      fr: "Time Converter - World Clock",
    },
    description: {
      en: "Plan meetings and travel across global time zones from your phone.",
      vi: "Lên kế hoạch họp và di chuyển qua các múi giờ toàn cầu ngay trên điện thoại.",
      hi: "अपने फोन से वैश्विक समय क्षेत्रों के अनुसार मीटिंग और यात्रा की योजना बनाएं।",
      km: "រៀបចំផែនការប្រជុំ និងការធ្វើដំណើរឆ្លងកាត់តំបន់ពេលវេលាពិភពលោកពីទូរស័ព្ទរបស់អ្នក។",
      th: "วางแผนการประชุมและการเดินทางข้ามเขตเวลาทั่วโลกจากโทรศัพท์ของคุณ",
      id: "Rencanakan rapat dan perjalanan lintas zona waktu global dari ponsel Anda.",
      fil: "Planuhin ang mga meeting at biyahe sa iba’t ibang global time zone mula sa iyong phone.",
      de: "Plane Meetings und Reisen ueber globale Zeitzonen hinweg direkt von deinem Smartphone.",
      fr: "Planifiez reunions et voyages a travers les fuseaux horaires mondiaux depuis votre telephone.",
    },
    category: {
      en: "Mobile",
      vi: "Di động",
      hi: "मोबाइल",
      km: "ទូរស័ព្ទ",
      th: "มือถือ",
      id: "Seluler",
      fil: "Mobile",
      de: "Mobil",
      fr: "Mobile",
    },
    stack: ["Next.js", "React Native"],
    image: "/graphic/time-converter.png",
    wide: false,
    appStoreLink:
      "https://apps.apple.com/us/app/time-converter-world-clock/id6780116305",
    playStoreLink:
      "https://play.google.com/store/apps/details?id=nexa.timeconverter.com",
  },
  {
    id: "quick-image-pdf-resizer",
    name: {
      en: "Quick Image PDF Resizer",
      vi: "Quick Image PDF Resizer",
      hi: "Quick Image PDF Resizer",
      km: "Quick Image PDF Resizer",
      th: "Quick Image PDF Resizer",
      id: "Quick Image PDF Resizer",
      fil: "Quick Image PDF Resizer",
      de: "Quick Image PDF Resizer",
      fr: "Quick Image PDF Resizer",
    },
    description: {
      en: "Resize images, compress files, convert formats, and handle common PDF tasks.",
      vi: "Thay đổi kích thước ảnh, nén tệp, chuyển đổi định dạng và xử lý các tác vụ PDF phổ biến.",
      hi: "इमेज का आकार बदलें, फाइलें कंप्रेस करें, फॉर्मेट कन्वर्ट करें और सामान्य PDF कार्य संभालें।",
      km: "ផ្លាស់ប្តូរទំហំរូបភាព បង្ហាប់ឯកសារ បម្លែងទ្រង់ទ្រាយ និងដោះស្រាយកិច្ចការទូទៅរបស់ PDF។",
      th: "ปรับขนาดภาพ บีบอัดไฟล์ แปลงรูปแบบ และจัดการงาน PDF ทั่วไป",
      id: "Ubah ukuran gambar, kompres file, konversi format, dan tangani tugas PDF umum.",
      fil: "Mag-resize ng images, mag-compress ng files, mag-convert ng formats, at humawak ng karaniwang PDF tasks.",
      de: "Passe Bildgroessen an, komprimiere Dateien, konvertiere Formate und erledige gaengige PDF-Aufgaben.",
      fr: "Redimensionnez des images, compressez des fichiers, convertissez des formats et gerez les taches PDF courantes.",
    },
    category: {
      en: "Mobile",
      vi: "Di động",
      hi: "मोबाइल",
      km: "ទូរស័ព្ទ",
      th: "มือถือ",
      id: "Seluler",
      fil: "Mobile",
      de: "Mobil",
      fr: "Mobile",
    },
    stack: ["React Native", "PDF", "Image Tools"],
    image: "/graphic/resize-image.png",
    wide: false,
    appStoreLink:
      "https://apps.apple.com/us/app/quick-image-pdf-resizer/id6780742651",
    playStoreLink:
      "https://play.google.com/store/apps/details?id=com.nexa.pdfresizer",
  },
  {
    id: "world-time-buddy",
    name: {
      en: "World Time Buddy",
      vi: "World Time Buddy",
      hi: "World Time Buddy",
      km: "World Time Buddy",
      th: "World Time Buddy",
      id: "World Time Buddy",
      fil: "World Time Buddy",
      de: "World Time Buddy",
      fr: "World Time Buddy",
    },
    description: {
      en: "A lightweight Chrome extension for comparing time zones while you work.",
      vi: "Tiện ích mở rộng Chrome gọn nhẹ để so sánh múi giờ trong khi làm việc.",
      hi: "काम करते समय समय क्षेत्रों की तुलना करने के लिए एक हल्का Chrome एक्सटेंशन।",
      km: "ផ្នែកបន្ថែម Chrome ស្រាលមួយសម្រាប់ប្រៀបធៀបតំបន់ពេលវេលា ខណៈពេលអ្នកកំពុងធ្វើការ។",
      th: "ส่วนขยาย Chrome น้ำหนักเบาสำหรับเปรียบเทียบเขตเวลาระหว่างทำงาน",
      id: "Ekstensi Chrome ringan untuk membandingkan zona waktu saat Anda bekerja.",
      fil: "Isang magaang na Chrome extension para ihambing ang mga time zone habang nagtatrabaho ka.",
      de: "Eine leichte Chrome-Erweiterung zum Vergleichen von Zeitzonen waehrend der Arbeit.",
      fr: "Une extension Chrome legere pour comparer les fuseaux horaires pendant que vous travaillez.",
    },
    category: {
      en: "Extension",
      vi: "Tiện ích mở rộng",
      hi: "एक्सटेंशन",
      km: "ផ្នែកបន្ថែម",
      th: "ส่วนขยาย",
      id: "Ekstensi",
      fil: "Extension",
      de: "Erweiterung",
      fr: "Extension",
    },
    stack: ["Chrome Extension", "Time Zones", "Productivity"],
    image: "/graphic/time-converter-extension.png",
    wide: true,
    link: "https://chromewebstore.google.com/detail/world-time-buddy/mmlplefhfbacmbebleofnfligokkaljh",
  },
];
